package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Unarr-app/unarr-cli/internal/agent"
	"github.com/Unarr-app/unarr-cli/internal/config"
	"github.com/Unarr-app/unarr-cli/internal/ui"
	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

func newCleanCmd() *cobra.Command {
	var (
		dryRun   bool
		all      bool
		yes      bool
		hlsCache bool
	)

	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Remove temporary files, logs, and cached data",
		Long: `Remove temporary files, logs, resume data, and other artifacts generated by unarr.

Shows what will be removed and asks for confirmation before deleting.

By default, cleans:
  - Log files (unarr.log, unarr.err.log) and their rotated copies (.1, .2, …)
  - Daemon state file (daemon.state.json)
  - Stale usenet resume files older than 7 days (.progress, .nzb cache)
  - Stale replaced-file backups older than 7 days (from library upgrades)
  - Stream temp directory (/tmp/unarr-stream/)
  - Upgrade temp files (/tmp/unarr-download-*.tmp)
  - Stale atomic-write temp files (.tmp)

Recent usenet resume files (< 7 days) are kept to preserve download
progress for paused or interrupted downloads.

With --hls-cache, also removes:
  - The transcoded HLS segment cache (~/.cache/unarr/hls-cache/ on Linux,
    ~/Library/Caches/unarr/hls-cache/ on macOS, %LOCALAPPDATA%\unarr\hls-cache\
    on Windows, or hls_cache.dir when set)

Clearing the HLS cache costs nothing but re-encoding time: the next play of
each title transcodes again from the source. Use it to reclaim disk, or if a
title stops playing partway through.

With --all, also removes:
  - ALL usenet resume files (including recent ones)
  - The HLS segment cache
  - The entire data directory (~/.local/share/unarr/ on Linux,
    ~/Library/Application Support/unarr/ on macOS, %LOCALAPPDATA%\unarr\ on Windows)

Never removes:
  - Configuration file (config.toml)
  - Downloaded media files
  - Partial torrent or debrid downloads (stored in your download dir)`,
		Example: `  unarr clean              # Show files and confirm before removing
  unarr clean --dry-run    # Show what would be removed (no prompt)
  unarr clean --yes        # Skip confirmation
  unarr clean --hls-cache  # Also remove transcoded HLS segments
  unarr clean --all        # Also remove the data directory`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runClean(cleanOpts{dryRun: dryRun, all: all, yes: yes, hlsCache: hlsCache})
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "show what would be removed without deleting")
	cmd.Flags().BoolVar(&all, "all", false, "also remove the entire data directory")
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "skip confirmation prompt")
	cmd.Flags().BoolVar(&hlsCache, "hls-cache", false, "also remove transcoded HLS segments")

	return cmd
}

// cleanOpts carries the command's flags. A struct rather than four positional
// booleans, which no call site could read back correctly.
type cleanOpts struct {
	dryRun   bool
	all      bool
	yes      bool
	hlsCache bool
}

func runClean(o cleanOpts) error {
	dryRun, all, yes := o.dryRun, o.all, o.yes
	bold := color.New(color.Bold)
	green := color.New(color.FgGreen)
	yellow := color.New(color.FgYellow)
	dim := color.New(color.FgHiBlack)

	// Check if daemon is running
	if state := agent.ReadState(); state != nil && state.PID > 0 {
		if agent.IsProcessAlive(state.PID) {
			return fmt.Errorf("daemon is running (PID %d) — stop it first with Ctrl+C or 'unarr stop'", state.PID)
		}
	}

	dataDir := config.DataDir()
	targets := cleanTargetsFor(o, dataDir)

	// Phase 1: Scan and collect what exists
	found, totalFiles, totalBytes := scanCleanTargets(targets)

	// Age-filtered extras (resume + replaced backups). Skipped under --all,
	// which already sweeps them through the whole-dataDir target.
	aged, resumeSkipped := scanAgedExtras(dataDir, all)
	for _, e := range aged {
		totalFiles++
		totalBytes += e.size
		found = append(found, e)
	}

	// Phase 2: Show what was found
	fmt.Println()
	bold.Println("  unarr clean")
	fmt.Println()

	if totalFiles == 0 {
		dim.Println("  Nothing to clean.")
		fmt.Println()
		return nil
	}

	fmt.Println("  Files to remove:")
	fmt.Println()
	for _, e := range found {
		display := shortenHome(e.path)
		fmt.Printf("    %s ", display)
		dim.Printf("(%s, %s)\n", e.desc, ui.FormatBytes(e.size))
	}
	fmt.Println()
	bold.Printf("  Total: %d file(s), %s\n", totalFiles, ui.FormatBytes(totalBytes))
	if resumeSkipped > 0 {
		dim.Printf("  Kept %d recent resume file(s) (< 7 days) — use --all to include\n", resumeSkipped)
	}
	fmt.Println()

	// Phase 3: Dry run stops here
	if dryRun {
		yellow.Println("  Dry run — nothing will be deleted.")
		fmt.Println()
		return nil
	}

	// Phase 4: Ask for confirmation (unless --yes)
	if !yes && !confirmClean() {
		fmt.Println()
		yellow.Println("  Aborted.")
		fmt.Println()
		return nil
	}

	// Phase 5: Delete
	freed, failed := deleteCleanEntries(found, green)

	fmt.Println()
	// Report the reclaimed bytes, not the surveyed total: a directory entry
	// that failed to delete covers many files, so subtracting failures from
	// the file count would be wrong in both directions.
	green.Printf("  ✓ Freed %s\n", ui.FormatBytes(freed))
	if failed > 0 {
		yellow.Printf("  %d entr(y/ies) could not be removed — see above\n", failed)
	}
	fmt.Println()

	return nil
}

// confirmClean prompts for the interactive y/N confirmation. Anything other
// than an explicit yes means no — this deletes files, so a stray newline or a
// closed stdin must not be read as consent.
func confirmClean() bool {
	fmt.Print("  Proceed? [y/N] ")
	scanner := bufio.NewScanner(os.Stdin)
	scanner.Scan()
	answer := strings.TrimSpace(strings.ToLower(scanner.Text()))
	return answer == "y" || answer == "yes"
}

// deleteCleanEntries removes each entry and prints it as it goes. Failures are
// not fatal: one undeletable path (open handle, permissions) should not stop
// the rest of the cleanup, and the entry is simply not ticked off.
// Returns the bytes actually reclaimed, so the summary reports what happened
// rather than what was planned.
func deleteCleanEntries(found []foundEntry, green *color.Color) (freedBytes int64, failed int) {
	for _, e := range found {
		var err error
		if e.isDir {
			err = os.RemoveAll(strings.TrimSuffix(e.path, "/"))
		} else {
			err = os.Remove(e.path)
		}
		display := shortenHome(e.path)
		if err != nil {
			fmt.Printf("  ✗ %s (%v)\n", display, err)
			failed++
			continue
		}
		freedBytes += e.size
		green.Print("  ✓ ")
		fmt.Println(display)
	}
	return freedBytes, failed
}

// scanResumeFiles scans the resume directory for cleanable files.
// If all is true, returns all files. Otherwise only stale files (>7 days).
func scanResumeFiles(resumeDir string, all bool) (found []foundEntry, skipped int) {
	entries, err := os.ReadDir(resumeDir)
	if err != nil {
		return nil, 0
	}

	const staleAge = 7 * 24 * time.Hour

	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		info, err := e.Info()
		if err != nil {
			continue
		}

		isStale := time.Since(info.ModTime()) > staleAge
		if !all && !isStale {
			skipped++
			continue
		}

		path := filepath.Join(resumeDir, e.Name())
		desc := "stale resume file"
		if all && !isStale {
			desc = "resume file"
		}
		found = append(found, foundEntry{path, desc, info.Size(), false})
	}
	return found, skipped
}

// scanReplacedFiles scans the replaced/ backup dir (old files kept by organize's
// replaceFile on each upgrade). If all is true, returns everything; otherwise only
// stale backups (>7 days). Same staleness policy as scanResumeFiles so `clean`
// treats both aging-artifact dirs consistently.
func scanReplacedFiles(replacedDir string, all bool) []foundEntry {
	entries, err := os.ReadDir(replacedDir)
	if err != nil {
		return nil // dir absent (no upgrades yet) — nothing to sweep
	}

	const staleAge = 7 * 24 * time.Hour
	var found []foundEntry

	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		info, err := e.Info()
		if err != nil {
			continue
		}
		if !all && time.Since(info.ModTime()) <= staleAge {
			continue // recent backup — keep it (a just-upgraded file the user may want back)
		}
		desc := "stale replaced backup"
		if all {
			desc = "replaced backup"
		}
		found = append(found, foundEntry{filepath.Join(replacedDir, e.Name()), desc, info.Size(), false})
	}
	return found
}

func shortenHome(path string) string {
	home, _ := os.UserHomeDir()
	if home != "" {
		return strings.Replace(path, home, "~", 1)
	}
	return path
}

func dirStats(dir string) (int, int64) {
	var files int
	var bytes int64
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() {
			files++
			bytes += info.Size()
		}
		return nil
	})
	return files, bytes
}

func fileSize(path string) int64 {
	info, err := os.Stat(path)
	if err != nil {
		return 0
	}
	return info.Size()
}

// globSize totals the files matching a shell pattern. Used for the artifact
// families whose exact names aren't known up front — rotated logs, upgrade
// temp files.
func globSize(pattern string) int64 {
	matches, _ := filepath.Glob(pattern)
	var total int64
	for _, m := range matches {
		total += fileSize(m)
	}
	return total
}

// CleanableBytes calculates the total size of files that would be safe to clean
// right now. Called from the daemon heartbeat to report cleanable space.
// Excludes daemon.state.json (actively written while daemon runs) and
// recent resume files (< 7 days, needed for download resume).
func CleanableBytes() int64 {
	dataDir := config.DataDir()
	tmpDir := os.TempDir()
	var total int64

	// Logs — the live files plus every rotated copy of the ring, from the same
	// list `clean` deletes, so the figure the daemon reports matches what
	// `unarr clean` would actually free.
	for _, t := range logCleanTargets(dataDir) {
		if t.isGlob {
			total += globSize(t.path)
			continue
		}
		total += fileSize(t.path)
	}

	// Stale resume files only (>7 days)
	resumeFound, _ := scanResumeFiles(filepath.Join(dataDir, "resume"), false)
	for _, e := range resumeFound {
		total += e.size
	}

	// Stale replaced-file backups only (>7 days) — RC-6: this dir grew unbounded.
	for _, e := range scanReplacedFiles(filepath.Join(dataDir, "replaced"), false) {
		total += e.size
	}

	// Stream temp
	_, streamBytes := dirStats(filepath.Join(tmpDir, "unarr-stream"))
	total += streamBytes

	// Upgrade temp files
	total += globSize(filepath.Join(tmpDir, "unarr-download-*.tmp"))

	// Config temp
	total += fileSize(config.FilePath() + ".tmp")

	return total
}
