package engine

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"time"
)

// netBenchPayloadBytes matches the /speedtest handler's cap (see
// speedtestHandler): asking for more just gets clamped, and asking for less
// makes the measurement shorter than TCP needs to open its window.
const netBenchPayloadBytes = 4 * 1024 * 1024

// netBenchTimeout bounds the whole probe. A daemon that cannot serve 4 MiB of
// pre-generated bytes in 30 s has a problem the number wouldn't describe
// anyway.
const netBenchTimeout = 30 * time.Second

// NetBenchResult is one round of the daemon's own HTTP surface: how fast it
// answers, and how fast it pushes bytes.
type NetBenchResult struct {
	BaseURL   string  `json:"baseUrl"`
	LatencyMS float64 `json:"latencyMs"`
	Bytes     int64   `json:"bytes"`
	Seconds   float64 `json:"seconds"`
	Mbps      float64 `json:"mbps"`
}

// BenchmarkStreamEndpoint measures the running daemon over baseURL by reusing
// the endpoints it already serves: /health for request latency and /speedtest
// for throughput. Nothing is reimplemented here — /speedtest exists precisely
// so a client can time a fixed, incompressible payload, and this is one more
// client of it.
//
// Over loopback this measures the agent's ability to SERVE, not the user's
// internet link; the renderer says so. It is still the number that matters
// when a local player stutters, and it is the same code path a remote viewer
// exercises.
func BenchmarkStreamEndpoint(ctx context.Context, baseURL string) (NetBenchResult, error) {
	res := NetBenchResult{BaseURL: baseURL}
	ctx, cancel := context.WithTimeout(ctx, netBenchTimeout)
	defer cancel()

	client := &http.Client{}
	latency, err := timeGET(ctx, client, baseURL+"/health", false)
	if err != nil {
		return res, fmt.Errorf("daemon not reachable at %s: %w", baseURL, err)
	}
	res.LatencyMS = float64(latency.Microseconds()) / 1000

	payloadURL := fmt.Sprintf("%s/speedtest?size=%d", baseURL, netBenchPayloadBytes)
	elapsed, err := timeGET(ctx, client, payloadURL, true)
	if err != nil {
		return res, fmt.Errorf("speedtest against %s: %w", baseURL, err)
	}
	res.Bytes = netBenchPayloadBytes
	res.Seconds = elapsed.Seconds()
	if res.Seconds > 0 {
		res.Mbps = float64(res.Bytes) * 8 / 1e6 / res.Seconds
	}
	return res, nil
}

// timeGET returns the wall time of a GET. When drain is true the body is read
// to completion and counted in the time (throughput); otherwise the body is
// discarded unread so the timing is response latency, not transfer.
func timeGET(ctx context.Context, client *http.Client, target string, drain bool) (time.Duration, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, target, nil)
	if err != nil {
		return 0, err
	}
	start := time.Now()
	resp, err := client.Do(req)
	if err != nil {
		// Unwrap *url.Error: its message repeats the method and the full URL,
		// which the caller is about to print anyway. What the user needs is the
		// cause ("connection refused"), not a third copy of the address.
		var uerr *url.Error
		if errors.As(err, &uerr) && uerr.Err != nil {
			return 0, uerr.Err
		}
		return 0, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("unexpected status %s", resp.Status)
	}
	if !drain {
		return time.Since(start), nil
	}
	if _, err := io.Copy(io.Discard, resp.Body); err != nil {
		return 0, err
	}
	return time.Since(start), nil
}
